name = "PrimeSquareSum"
version = "0.1.0"
keywords = ["math"]
defaultTargets = ["PrimeSquareSum"]

[leanOptions]
pp.unicode.fun = true       # pretty-prints `fun a â†¦ b`
relaxedAutoImplicit = false

[[require]]
name = "mathlib"
scope = "leanprover-community"
rev = "v4.27.0"

[[lean_lib]]
name = "PrimeSquareSum"
srcDir = "proofs"
roots = ["TriSum", "PrimesumMod6", "FiveTwo", "Primes", "Core"]
